<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Website</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f8f8;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            width: 100%;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            text-align: center;
        }
        .ad-banner {
            margin-top: 20px;
            padding: 20px;
            background-color: #f1f1f1;
            border: 1px solid #ddd;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .ad-banner h2 {
            color: #333;
            font-size: 24px;
            margin-bottom: 10px;
        }
        .ad-banner a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #ff0000;
            color: #fff;
            text-decoration: none;
            font-size: 18px;
            font-weight: bold;
            border-radius: 4px;
            transition: background-color 0.3s ease;
        }
        .ad-banner a:hover {
            background-color: #cc0000;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to My Website</h1>
        <p>Discover amazing content and stay updated with our latest news.</p>
        <div class="ad-banner">
            <h2>Check Out Our YouTube Channel!</h2>
            <a href="https://youtube.com/@sahibdeep_yt?si=CN43NJmHQeIZ4KKg" target="_blank">Visit SAHIBDEEP_YT</a>
        </div>
        <br>
        <p>Thank you for visiting!</p>
    </div>
</body>
</html>
